/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai1;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.exit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arohigh
 */
public class Form5 extends javax.swing.JFrame {

    ArrayList<SinhVienMM> ds = new ArrayList();
    ArrayList<SinhVienTT> ds2 = new ArrayList();
    String header[] = {"Mã SV","Họ Tên","Ngày sinh","Điểm trung bình","Lương","Học phí"};
    DefaultTableModel model = new DefaultTableModel(header,0);
    /**
     * Creates new form Form5
     */
    public Form5() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfMasv = new javax.swing.JTextField();
        tfHoten = new javax.swing.JTextField();
        tfNgaysinh = new javax.swing.JTextField();
        tfDiemTB = new javax.swing.JTextField();
        tfHocphi = new javax.swing.JTextField();
        tfLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        svattt = new javax.swing.JRadioButton();
        svmm = new javax.swing.JRadioButton();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_sv = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("QUAN LY SINH VIEN");

        jLabel2.setText("MaSV");

        jLabel3.setText("HoTen");

        jLabel4.setText("Ngaysinh");

        jLabel5.setText("Diem TB");

        jLabel6.setText("Gioitinh");

        jLabel7.setText("Hocphi");

        jLabel9.setText("Luong");

        tfNgaysinh.setToolTipText("");

        jLabel10.setText("Loai SV");

        buttonGroup1.add(svattt);
        svattt.setText("SVTT");
        svattt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svatttActionPerformed(evt);
            }
        });

        buttonGroup1.add(svmm);
        svmm.setText("SVMM");
        svmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmmActionPerformed(evt);
            }
        });

        buttonGroup2.add(nam);
        nam.setText("Nam");

        buttonGroup2.add(nu);
        nu.setText("Nu");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tb_sv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaSV", "Ho ten", "Diem TB", "Loai", "Hoc phi", "Luong"
            }
        ));
        jScrollPane2.setViewportView(tb_sv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfHocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(svattt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(svmm))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nam)
                                        .addGap(18, 18, 18)
                                        .addComponent(nu))
                                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDiemTB, tfHocphi, tfHoten, tfLuong, tfMasv, tfNgaysinh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nam)
                    .addComponent(nu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(svattt)
                            .addComponent(svmm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfHocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnAdd)
                    .addComponent(btnExit)
                    .addComponent(btnReset))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void svatttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svatttActionPerformed
        // TODO add your handling code here:
        tfHocphi.setEnabled(true);

        tfLuong.setEnabled(false);
    }//GEN-LAST:event_svatttActionPerformed

    private void svmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svmmActionPerformed
        // TODO add your handling code here:
        tfHocphi.setEnabled(false);

        tfLuong.setEnabled(true);
    }//GEN-LAST:event_svmmActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (!svattt.isSelected() && !svmm.isSelected()) {
            JOptionPane.showMessageDialog(null, "ban phai chon loai Sinh vien truoc da");
            return;
        } else {
            if (svattt.isSelected()) {
                if (KiemTraRongSVATTT() == false) {
                    try {
                        SinhVienTT at = new SinhVienTT(tfMasv.getText(), tfHoten.getText(), tfNgaysinh.getText(), nam.isSelected() ? "nam" : "nu",
                                Float.parseFloat(tfDiemTB.getText()), Float.parseFloat(tfHocphi.getText()));
                        FileWriter fw = new FileWriter("svat.dat", true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        bw.append(at.MaSV + "$" + at.HoTen + "$" + at.NgaySinh + "$" + at.GioiTinh + "$" + at.DiemTB + "$" + at.getHocPhi());
                        bw.newLine();
                        bw.close();
                        fw.close();
                        JOptionPane.showMessageDialog(null, "luu file SVATTT thanh cong");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "luu file that bai");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ban chua nhap du thong tin cho SVATTT");
                    return;
                }
            } else {
                if (KiemTraRongSVMM() == false) {
                    try {
                        SinhVienMM mm;
                        mm = new SinhVienMM(tfMasv.getText(), tfHoten.getText(), tfNgaysinh.getText(), nam.isSelected() ? "nam" : "nu",
                                Float.parseFloat(tfDiemTB.toString()), Float.parseFloat(tfLuong.getText()));
                        FileWriter fw = new FileWriter("svmm.dat", true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        bw.append(mm.MaSV + "$" + mm.HoTen + "$" + mm.NgaySinh + "$" + mm.GioiTinh + "$" + mm.DiemTB + "$" + "$" + mm.getLuong());
                        bw.newLine();
                        bw.close();
                        fw.close();
                        JOptionPane.showMessageDialog(null, "luu file SVMM thanh cong");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "luu file that bai");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ban chua nhap du thong tin cho SVMM");
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String empty="";
        if ((tfHoten.getText().equals(empty))||(tfNgaysinh.getText().equals(empty)) ||(tfMasv.getText().equals(empty)) ){
            JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ thông tin!");
        }
        if (svmm.isSelected()){
            SinhVienMM m =new SinhVienMM();
            m.setMaSV(tfMasv.getText());
            m.setHoTen(tfHoten.getText());
            m.setGioiTinh(buttonGroup2.getSelection().toString());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
               
            } catch (ParseException ex) {
                Logger.getLogger(Form5.class.getName()).log(Level.SEVERE,null,ex);
            }
            try {
                m.setDiemTB(Float.parseFloat(tfDiemTB.getText()));
                m.setLuong(Float.parseFloat(tfLuong.getText()));} catch (NumberFormatException e) {
            }
            ds.add(m);
            model.addRow(new Object[]{m.getMaSV(), m.getHoTen(), m.getNgaySinh(), m.getDiemTB(),m.getLuong(),""});
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công 1 SVMM!");
        }
        else
        if (svattt.isSelected()){
            SinhVienTT t = new SinhVienTT();
            t.setMaSV(tfMasv.getText());
            t.setHoTen(tfMasv.getText());
            t.setGioiTinh(buttonGroup2.getSelection().toString());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                
            } catch (ParseException ex) {
                Logger.getLogger(Form5.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                t.setDiemTB(Float.parseFloat(tfDiemTB.getText()));
                t.setHocPhi(Float.parseFloat(tfHocphi.getText()));
            } catch (NumberFormatException e) {
            }
            ds2.add(t);
            System.out.println(t.toString());
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công 1 SVTT!");
            model.addRow(new Object[]{t.getMaSV(), t.getHoTen(), t.getNgaySinh(), t.getDiemTB(),"",t.getHocPhi()});
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Chọn loại sinh viên!!!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfHoten.setText("");
        buttonGroup1.clearSelection();
        tfDiemTB.setText("");
        tfHocphi.setText("");
        buttonGroup2.clearSelection();
        tfMasv.setText("");
        tfNgaysinh.setText("");
        tfLuong.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form5().setVisible(true);
            }
        });
    }

    public boolean KiemTraRongSVATTT() {
        if (tfMasv.getText().equals("") || tfHoten.getText().equals("") || tfNgaysinh.getText().equals("") || tfDiemTB.getText().equals("")
                || tfHocphi.getText().equals("") || (!nam.isSelected() && !nu.isSelected())) {
            return true;
        }
        return false;
    }

    public boolean KiemTraRongSVMM() {
        if (tfMasv.getText().equals("") || tfHoten.getText().equals("") || tfNgaysinh.getText().equals("") || tfDiemTB.getText().equals("")
                || tfLuong.getText().equals("") || (!nam.isSelected() && !nu.isSelected())) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JRadioButton svattt;
    private javax.swing.JRadioButton svmm;
    private javax.swing.JTable tb_sv;
    private javax.swing.JTextField tfDiemTB;
    private javax.swing.JTextField tfHocphi;
    private javax.swing.JTextField tfHoten;
    private javax.swing.JTextField tfLuong;
    private javax.swing.JTextField tfMasv;
    private javax.swing.JTextField tfNgaysinh;
    // End of variables declaration//GEN-END:variables
}
